"""empty message

Revision ID: 46d48f272337
Revises: 
Create Date: 2019-04-16 10:33:14.803299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46d48f272337'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ion_transaction_type')
    op.drop_table('ion_vehicle_brand')
    op.drop_table('ion_kelurahan')
    op.drop_table('ion_ion_obu_detail')
    op.drop_table('ion_vehicle_type')
    op.drop_table('ion_wallet')
    op.drop_table('ion_log_activity')
    op.drop_table('ion_correspondent_address')
    op.drop_table('ion_activity_wallet')
    op.drop_table('ion_term_of_service')
    op.drop_table('ion_provider')
    op.drop_table('ion_city')
    op.drop_index('ix_ion_roles_default', table_name='ion_roles')
    op.drop_index('name', table_name='ion_roles')
    op.drop_table('ion_roles')
    op.drop_table('ion_point')
    op.drop_table('ion_topup_detail')
    op.drop_table('ion_plate_expired')
    op.drop_table('ion_help_category')
    op.drop_table('ion_help')
    op.drop_table('ion_topup_description')
    op.drop_table('ion_users')
    op.drop_table('ion_identity')
    op.drop_table('ion_postal_code')
    op.drop_table('ion_notification')
    op.drop_table('ion_notification_type')
    op.drop_table('ion_topup_list')
    op.drop_table('ion_vehicle_color')
    op.drop_table('ion_messages')
    op.drop_table('ion_trx_status')
    op.drop_index('ix_ion_bank_list_uid', table_name='ion_bank_list')
    op.drop_table('ion_bank_list')
    op.drop_table('ion_bank_account')
    op.drop_table('ion_image_gallery')
    op.drop_table('ion_privacy_policy')
    op.drop_table('ion_activity_type')
    op.drop_table('ion_province')
    op.drop_table('ion_image_title')
    op.drop_table('ion_product_type')
    op.drop_table('ion_obu_list')
    op.drop_table('ion_vehicle_series')
    op.drop_table('ion_product_category')
    op.drop_table('ion_vehicle_model')
    op.drop_table('ion_image_service')
    op.drop_table('ion_kecamatan')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ion_kecamatan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['ion_city.id'], name='ion_kecamatan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_image_service',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_title_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('verification_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_title_id'], ['ion_image_title.id'], name='ion_image_service_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_image_service_ibfk_1'),
    sa.ForeignKeyConstraint(['verification_id'], ['ion_trx_status.id'], name='ion_image_service_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_vehicle_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_product_category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('provider_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ion_image_gallery.id'], name='ion_product_category_ibfk_2'),
    sa.ForeignKeyConstraint(['provider_id'], ['ion_provider.id'], name='ion_product_category_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_vehicle_series',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['ion_vehicle_brand.id'], name='ion_vehicle_series_ibfk_1'),
    sa.ForeignKeyConstraint(['model_id'], ['ion_vehicle_model.id'], name='ion_vehicle_series_ibfk_3'),
    sa.ForeignKeyConstraint(['type_id'], ['ion_vehicle_type.id'], name='ion_vehicle_series_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_obu_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('obu_uid', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pin_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('use_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expired_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_obu_list_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_product_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['ion_activity_wallet.id'], name='ion_product_type_ibfk_2'),
    sa.ForeignKeyConstraint(['category_id'], ['ion_product_category.id'], name='ion_product_type_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_image_title',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_province',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_activity_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_privacy_policy',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_image_gallery',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('image_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_bank_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('account_name', mysql.VARCHAR(length=124), nullable=True),
    sa.Column('account_number', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['ion_bank_list.id'], name='ion_bank_account_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_bank_account_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_bank_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('uid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ion_bank_list_uid', 'ion_bank_list', ['uid'], unique=True)
    op.create_table('ion_trx_status',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_vehicle_color',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_topup_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('transaction_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ion_image_gallery.id'], name='ion_topup_list_ibfk_1'),
    sa.ForeignKeyConstraint(['transaction_type'], ['ion_transaction_type.id'], name='ion_topup_list_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_notification_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('page', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_notification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notification_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_type'], ['ion_notification_type.id'], name='ion_notification_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_notification_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_postal_code',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('kelurahan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kelurahan_id'], ['ion_kelurahan.id'], name='ion_postal_code_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_identity',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('profile_photo', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('nik', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('province_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('kecamatan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('kelurahan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('postal_code_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('photo_ktp', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('selfie_idcard', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['ion_city.id'], name='ion_identity_ibfk_3'),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['ion_kecamatan.id'], name='ion_identity_ibfk_4'),
    sa.ForeignKeyConstraint(['kelurahan_id'], ['ion_kelurahan.id'], name='ion_identity_ibfk_5'),
    sa.ForeignKeyConstraint(['postal_code_id'], ['ion_postal_code.id'], name='ion_identity_ibfk_6'),
    sa.ForeignKeyConstraint(['province_id'], ['ion_province.id'], name='ion_identity_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_identity_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('pin_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('firebase_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tos_agreement', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('refferal', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ion_roles.id'], name='ion_users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_topup_description',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('detail_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['ion_topup_detail.id'], name='ion_topup_description_ibfk_1'),
    sa.ForeignKeyConstraint(['image_id'], ['ion_image_gallery.id'], name='ion_topup_description_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_help',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ion_help_category.id'], name='ion_help_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_help_category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=125), nullable=True),
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ion_image_gallery.id'], name='ion_help_category_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_plate_expired',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('plate_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('obu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expired_month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expired_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obu_id'], ['ion_obu_list.id'], name='ion_plate_expired_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_plate_expired_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_topup_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('list_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['ion_topup_list.id'], name='ion_topup_detail_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_point',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['ion_product_category.id'], name='ion_point_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_point_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'ion_roles', ['name'], unique=True)
    op.create_index('ix_ion_roles_default', 'ion_roles', ['default'], unique=False)
    op.create_table('ion_city',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('province_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['ion_province.id'], name='ion_city_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_provider',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_term_of_service',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_activity_wallet',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_correspondent_address',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('province_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('kecamatan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('kelurahan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('postal_code_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address_detail', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['ion_city.id'], name='ion_correspondent_address_ibfk_3'),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['ion_kecamatan.id'], name='ion_correspondent_address_ibfk_4'),
    sa.ForeignKeyConstraint(['kelurahan_id'], ['ion_kelurahan.id'], name='ion_correspondent_address_ibfk_5'),
    sa.ForeignKeyConstraint(['postal_code_id'], ['ion_postal_code.id'], name='ion_correspondent_address_ibfk_6'),
    sa.ForeignKeyConstraint(['province_id'], ['ion_province.id'], name='ion_correspondent_address_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_correspondent_address_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_log_activity',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activity_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['ion_activity_type.id'], name='ion_log_activity_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_log_activity_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_wallet',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['ion_activity_wallet.id'], name='ion_wallet_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_wallet_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_vehicle_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_ion_obu_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('obu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('plate_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_series_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_color_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('plate_photo_front', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('plate_photo_back', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('vehicle_photo_front', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('vehicle_photo_back', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obu_id'], ['ion_obu_list.id'], name='ion_ion_obu_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_ion_obu_detail_ibfk_2'),
    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['ion_vehicle_brand.id'], name='ion_ion_obu_detail_ibfk_4'),
    sa.ForeignKeyConstraint(['vehicle_color_id'], ['ion_vehicle_color.id'], name='ion_ion_obu_detail_ibfk_7'),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['ion_vehicle_model.id'], name='ion_ion_obu_detail_ibfk_6'),
    sa.ForeignKeyConstraint(['vehicle_series_id'], ['ion_vehicle_series.id'], name='ion_ion_obu_detail_ibfk_5'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['ion_vehicle_type.id'], name='ion_ion_obu_detail_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_kelurahan',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('kecamatan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['ion_kecamatan.id'], name='ion_kelurahan_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_vehicle_brand',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['ion_vehicle_type.id'], name='ion_vehicle_brand_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_transaction_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ion_ion_obu_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obu_id', sa.Integer(), nullable=True),
    sa.Column('plate_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_brand_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_series_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_model_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_color_id', sa.Integer(), nullable=True),
    sa.Column('plate_photo_front', sa.String(length=128), nullable=True),
    sa.Column('plate_photo_back', sa.String(length=128), nullable=True),
    sa.Column('vehicle_photo_front', sa.String(length=128), nullable=True),
    sa.Column('vehicle_photo_back', sa.String(length=128), nullable=True),
    sa.Column('added_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['obu_id'], ['ion_obu_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['ion_vehicle_brand.id'], ),
    sa.ForeignKeyConstraint(['vehicle_color_id'], ['ion_vehicle_color.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['ion_vehicle_model.id'], ),
    sa.ForeignKeyConstraint(['vehicle_series_id'], ['ion_vehicle_series.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['ion_vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ion_inbox')
    op.drop_table('ion_obu_detail')
    op.drop_column('ion_bank_account', 'default')
    op.drop_constraint('ion_bank_list_ibfk_1', 'ion_bank_list', type_='foreignkey')
    op.drop_column('ion_bank_list', 'image_id')
    op.add_column('ion_obu_list', sa.Column('expired_date', sa.Date(), nullable=True))
    op.drop_column('ion_topup_detail', 'code_bank')
    op.drop_column('ion_users', 'mandiri_va')
    op.drop_column('ion_users', 'bca_va')
    op.drop_column('ion_users', 'bri_va')
    op.drop_column('ion_users', 'bni_va')
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ion_users', sa.Column('bni_va', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('ion_users', sa.Column('bri_va', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('ion_users', sa.Column('bca_va', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('ion_users', sa.Column('mandiri_va', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('ion_topup_detail', sa.Column('code_bank', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('ion_obu_list', 'expired_date')
    op.add_column('ion_bank_list', sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ion_bank_list_ibfk_1', 'ion_bank_list', 'ion_image_gallery', ['image_id'], ['id'])
    op.add_column('ion_bank_account', sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_table('ion_obu_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('obu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('plate_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_series_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehicle_color_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('plate_photo_front', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('plate_photo_back', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('vehicle_photo_front', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('vehicle_photo_back', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obu_id'], ['ion_obu_list.id'], name='ion_obu_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['ion_users.id'], name='ion_obu_detail_ibfk_2'),
    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['ion_vehicle_brand.id'], name='ion_obu_detail_ibfk_4'),
    sa.ForeignKeyConstraint(['vehicle_color_id'], ['ion_vehicle_color.id'], name='ion_obu_detail_ibfk_7'),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['ion_vehicle_model.id'], name='ion_obu_detail_ibfk_6'),
    sa.ForeignKeyConstraint(['vehicle_series_id'], ['ion_vehicle_series.id'], name='ion_obu_detail_ibfk_5'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['ion_vehicle_type.id'], name='ion_obu_detail_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ion_inbox',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_category_id'], ['ion_product_category.id'], name='ion_inbox_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('ion_ion_obu_detail')
    # ### end Alembic commands ###

